const data = {
    "modules": [
        {"id":1,"code":"MKT202","name":"MKT202 Marketing Management","cu":5,"sem":"July","desc":"MKT202e Marketing Management aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":3,"code":"ANL203","name":"ANL203 Analytics for Decision-Making","cu":5,"sem":"Jan","desc":"ANL203e Analytics for Descision-Making aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":4,"code":"BUS201","name":"BUS201 Contract & Agency Law","cu":5,"sem":"July","desc":"BUS201e Contract & Agency Law aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":2,"code":"ACC202","name":"ACC202 Financial and Mangerial Accounting","cu":5,"sem":"July","desc":"ACC202e Financial and Mangerial Accounting aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":5,"code":"ECO202","name":"ECO202 Mangerial Economics","cu":5,"sem":"Jan","desc":"ECO202e Mangerial Economics aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":6,"code":"BUS204","name":"BUS204 Business Excellence","cu":5,"sem":"July","desc":"BUS204e Business Excellence aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":7,"code":"ANL201","name":"ANL201 Data Visualisation for Business","cu":2.5,"sem":"July","desc":"ipsum ANL201rimis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem"},
        {"id":8,"code":"SCO101","name":"SCO101 Why Do Good?","cu":2.5,"sem":"Jan","desc":"SCO101 Why Do Good? in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut"},
        {"id":9,"code":"SCO211","name":"SCO211 Science for Sustainability","cu":5,"sem":"Jan","desc":"Science for Sustainability rhoncus sed SCOstibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio"},
        {"id":10,"code":"ANL303","name":"ANL303 Fundamentals of Data Mining","cu":5,"sem":"July","desc":"penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor"},
        {"id":11,"code":"FEM513","name":"Ass, asiatic wild","cu":2.5,"sem":"July","desc":"posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra"},
        {"id":12,"code":"EZJ826","name":"Sally lightfoot crab","cu":2.5,"sem":"Jan","desc":"sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt"},
        {"id":13,"code":"PZB123","name":"Horned lark","cu":2.5,"sem":"July","desc":"in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque"},
        {"id":14,"code":"EEE881","name":"Beaver, american","cu":5,"sem":"July","desc":"ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio"},
        {"id":15,"code":"NGK853","name":"Bat, asian false vampire","cu":10,"sem":"July","desc":"a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam"},
        {"id":16,"code":"ENA409","name":"Madagascar fruit bat","cu":5,"sem":"Jan","desc":"iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui"},
        {"id":17,"code":"FUF564","name":"Hawk, ferruginous","cu":10,"sem":"Jan","desc":"mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus"},
        {"id":18,"code":"PJZ013","name":"Red-legged pademelon","cu":10,"sem":"July","desc":"ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus"},
        {"id":19,"code":"WSU526","name":"Tern, white-winged black","cu":5,"sem":"July","desc":"laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum"},
        {"id":20,"code":"NIF992","name":"Duck, white-faced whistling","cu":2.5,"sem":"July","desc":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at"},
        {"id":21,"code":"SSL217","name":"Feathertail glider","cu":5,"sem":"July","desc":"est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget"},
        {"id":22,"code":"BRD616","name":"Baboon, olive","cu":10,"sem":"July","desc":"quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus"},
        {"id":23,"code":"LXV007","name":"Pigeon, wood","cu":2.5,"sem":"Jan","desc":"volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros"},
        {"id":24,"code":"SDY460","name":"Duck, blue","cu":2.5,"sem":"Jan","desc":"sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit"},
        {"id":25,"code":"MIX001","name":"Superb starling","cu":5,"sem":"Jan","desc":"pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi"},
        {"id":26,"code":"VNK518","name":"Booby, masked","cu":5,"sem":"July","desc":"blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh"},
        {"id":27,"code":"CRJ830","name":"White-necked stork","cu":2.5,"sem":"Jan","desc":"id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus"},
        {"id":28,"code":"TYL539","name":"Common duiker","cu":5,"sem":"July","desc":"orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum"},
        {"id":29,"code":"JVI214","name":"Goose, andean","cu":5,"sem":"Jan","desc":"fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat"},
        {"id":30,"code":"VVP089","name":"Turaco, violet-crested","cu":10,"sem":"July","desc":"nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis"},
        {"id":31,"code":"YLU650","name":"Fairy penguin","cu":2.5,"sem":"July","desc":"convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id"},
        {"id":32,"code":"CUQ621","name":"Collared lizard","cu":2.5,"sem":"Jan","desc":"nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit"},
        {"id":33,"code":"AXF556","name":"Squirrel, palm","cu":2.5,"sem":"Jan","desc":"in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit"},
        {"id":34,"code":"SRW677","name":"Weaver, white-browed sparrow","cu":5,"sem":"July","desc":"dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem"},
        {"id":35,"code":"EBU772","name":"Guerza","cu":5,"sem":"Jan","desc":"ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis"},
        {"id":36,"code":"EGT336","name":"Blue fox","cu":5,"sem":"Jan","desc":"sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum"},
        {"id":37,"code":"GJQ076","name":"Egyptian vulture","cu":2.5,"sem":"Jan","desc":"vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at"},
        {"id":38,"code":"EQD818","name":"Blue catfish","cu":10,"sem":"Jan","desc":"ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio"},
        {"id":39,"code":"YMF674","name":"Greater roadrunner","cu":10,"sem":"Jan","desc":"odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus"},
        {"id":40,"code":"NIQ188","name":"Warthog","cu":10,"sem":"Jan","desc":"eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id"},
        {"id":41,"code":"YLL737","name":"Colobus, white-mantled","cu":5,"sem":"Jan","desc":"vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer"},
        {"id":42,"code":"CAB508","name":"Badger, eurasian","cu":5,"sem":"Jan","desc":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus"},
        {"id":43,"code":"WTM212","name":"Cat, kaffir","cu":10,"sem":"July","desc":"eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque"},
        {"id":44,"code":"MNP011","name":"Python, carpet","cu":5,"sem":"Jan","desc":"donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a"},
        {"id":45,"code":"TXA407","name":"Black-tailed prairie dog","cu":10,"sem":"Jan","desc":"dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia"},
        {"id":46,"code":"PCJ926","name":"Gonolek, burchell's","cu":5,"sem":"Jan","desc":"risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur"},
        {"id":47,"code":"AOY536","name":"Asian lion","cu":5,"sem":"Jan","desc":"sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat"},
        {"id":48,"code":"FVC343","name":"Magistrate black colobus","cu":10,"sem":"July","desc":"in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac"},
        {"id":49,"code":"EDL320","name":"Wolf, timber","cu":10,"sem":"Jan","desc":"vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut"},
        {"id":50,"code":"WSP511","name":"Porcupine, north american","cu":2.5,"sem":"Jan","desc":"penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque"},
    ],

    "module-info": [
        {
            "id": 1,
            "code": "MKT202",
            "name": "MKT202 Marketing Management",
            "desc": "MKT202e Marketing Management aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes.",
            "topics": [
                {"id": 1, "topicName": "Marketing Environment"},
                {"id": 2, "topicName": "Market Segments and Targets"},
                {"id": 3, "topicName": "Brand Positioning"},
                {"id": 4, "topicName": "Marketing of Products"},
                {"id": 5, "topicName": "Marketing of Services"},
                {"id": 6, "topicName": "Pricing Strategies & Programmes"}
            ],
            "learningOutcomes": [
                {"id": 1, "outcomeName": "Explain the key concepts of marketing"},
                {"id": 2, "outcomeName": "Discuss the factors in consumer management"},
                {"id": 3, "outcomeName": "Examine the market segmentation, targeting and positioning"}
            ],
            "textbook": "Philip Kotler, Kevin Lane Keller: Marketing Management Global Edition 15 Pearson ISBN-13: 9781292092713",
            "cu": 5,
            "sem": "Jul",
            "level": 2,
            "prerequsites": "-",
            "language": "English",
            "timeTable": "Monday, Week 1, Term 1"
        },

        {
            "id": 2,
            "code": "ANL203",
            "name": "ANL203 Analytics for Decision-Making",
            "desc": "ANL203 Analytics for Decision-Making aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes.",
            "topics": [
                {"id": 1, "topicName": "Marketing Environment"},
                {"id": 2, "topicName": "Market Segments and Targets"},
                {"id": 3, "topicName": "Brand Positioning"},
                {"id": 4, "topicName": "Marketing of Products"},
                {"id": 5, "topicName": "Marketing of Services"},
                {"id": 6, "topicName": "Pricing Strategies & Programmes"}
            ],
            "learningOutcomes": [
                {"id": 1, "outcomeName": "Explain the key concepts of marketing"},
                {"id": 2, "outcomeName": "Discuss the factors in consumer management"},
                {"id": 3, "outcomeName": "Examine the market segmentation, targeting and positioning"}
            ],
            "textbook": "Philip Kotler, Kevin Lane Keller: Marketing Management Global Edition 15 Pearson ISBN-13: 9781292092713",
            "cu": 5,
            "sem": "Jul",
            "level": 2,
            "prerequsites": "-",
            "language": "English",
            "timeTable": "Monday, Week 1, Term 1"
        }

    ]
}

export default data;