// TODO: remove file
const modules = [
        {"id":1,"code":"MKT202","name":"MKT202 Marketing Management","cu":5,"sem":"July","desc":"MKT202e Marketing Management aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":3,"code":"ANL203","name":"ANL203 Analytics for Decision-Making","cu":5,"sem":"Jan","desc":"ANL203e Analytics for Descision-Making aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":4,"code":"BUS201","name":"BUS201 Contract & Agency Law","cu":5,"sem":"July","desc":"BUS201e Contract & Agency Law aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":2,"code":"ACC202","name":"ACC202 Financial and Mangerial Accounting","cu":5,"sem":"July","desc":"ACC202e Financial and Mangerial Accounting aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":5,"code":"ECO202","name":"ECO202 Mangerial Economics","cu":5,"sem":"Jan","desc":"ECO202e Mangerial Economics aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":6,"code":"BUS204","name":"BUS204 Business Excellence","cu":5,"sem":"July","desc":"BUS204e Business Excellence aims to provide students with anintroduction to marketing management and seeks to provide insights into the key concepts and general activities associatedwith the marketing function. It focuses on the fundamentals of consumer behavior, market research,segmentation, target marketing and positioning, branding and marketing mix management. The coursealso aims to build students' knowledge and skills in the managerial aspects of marketing with afocus on the development and execution of marketing plans and programmes."},
        {"id":7,"code":"ANL201","name":"ANL201 Data Visualisation for Business","cu":2.5,"sem":"July","desc":"ipsum ANL201rimis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem"},
        {"id":8,"code":"SCO101","name":"SCO101 Why Do Good?","cu":2.5,"sem":"Jan","desc":"SCO101 Why Do Good? in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut"},
        {"id":9,"code":"SCO211","name":"SCO211 Science for Sustainability","cu":5,"sem":"Jan","desc":"Science for Sustainability rhoncus sed SCOstibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio"},
        {"id":10,"code":"ANL303","name":"ANL303 Fundamentals of Data Mining","cu":5,"sem":"July","desc":"penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor"},
]

export default modules;